In [2]:
import pandas as pd
import numpy as np

dataset = pd.read_csv("Progetto computer science\\adoptions\\dogs.csv")
dataset1 = pd.read_csv("Progetto computer science\\adoptions\\dogTravel.csv")
dataset2 = pd.read_csv("Progetto computer science\\adoptions\\NST-EST2021-POP.csv")

dataset.head()

,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,...,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description,stay_duration,stay_cost
0,46042150,NV163,https://www.petfinder.com/dog/harley-46042150/...,Dog,Dog,American Staffordshire Terrier,Mixed Breed,True,False,White / Cream,...,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,Harley is not sure how he wound up at shelter ...,70,124.81
1,46042002,NV163,https://www.petfinder.com/dog/biggie-46042002/...,Dog,Dog,Pit Bull Terrier,Mixed Breed,True,False,Brown / Chocolate,...,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,6 year old Biggie has lost his home and really...,49,122.07
2,46040898,NV99,https://www.petfinder.com/dog/ziggy-46040898/n...,Dog,Dog,Shepherd,NaN,False,False,Brindle,...,Mesquite,NV,89027,US,89009,2019-09-20,Dog,Approx 2 years old.\n Did I catch your eye? I ...,87,281.51
3,46039877,NV202,https://www.petfinder.com/dog/gypsy-46039877/n...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,...,Pahrump,NV,89048,US,89009,2019-09-20,Dog,NaN,62,145.83
4,46039306,NV184,https://www.petfinder.com/dog/theo-46039306/nv...,Dog,Dog,Dachshund,NaN,False,False,NaN,...,Henderson,NV,89052,US,89009,2019-09-20,Dog,Theo is a friendly dachshund mix who gets alon...,93,241.09

In [9]:
dataset1.head()

,index,id,contact_city,contact_state,description,found,manual,remove,still_there
0,0,44520267,Anoka,MN,Boris is a handsome mini schnauzer who made hi...,Arkansas,NaN,NaN,NaN
1,1,44698509,Groveland,FL,Duke is an almost 2 year old Potcake from Abac...,Abacos,Bahamas,NaN,NaN
2,2,45983838,Adamstown,MD,Zac Woof-ron is a heartthrob movie star lookin...,Adam,Maryland,NaN,NaN
3,3,44475904,Saint Cloud,MN,~~Came in to the shelter as a transfer from an...,Adaptil,NaN,True,NaN
4,4,43877389,Pueblo,CO,Palang is such a sweetheart. She loves her peo...,Afghanistan,NaN,NaN,NaN

In [10]:
dataset2.head()

      Alabama   5.024.279
0      Alaska     733.391
1     Arizona   7.151.502
2    Arkansas   3.011.524
3  California  39.538.223
4    Colorado   5.773.714

**1. Extract all dogs with status that is not adoptable**

In [11]:
#controllo dati unici presenti
valori_unici = dataset['status'].unique()
valori_unici

array(['adoptable', '2018-04-05T05:18:31+0000',
       '2017-05-26T21:43:16+0000', '2019-09-01T15:12:06+0000',
       '2019-08-06T12:15:58+0000', '2019-07-18T14:20:58+0000',
       '2019-07-11T20:34:42+0000', '2019-07-11T14:16:38+0000',
       '2019-08-10T16:00:35+0000', '2019-05-14T21:09:27+0000',
       '2016-12-15T13:33:43+0000', '2015-09-07T12:57:27+0000',
       '2018-07-05T00:55:08+0000', '2017-10-07T23:48:20+0000',
       '2019-09-07T04:09:12+0000', '2019-09-13T19:39:28+0000',
       '2019-04-25T01:56:52+0000', '2018-04-18T13:45:46+0000',
       '2019-09-08T18:21:21+0000', '2019-07-25T19:53:21+0000',
       '2015-06-29T23:58:09+0000', '2015-02-07T13:06:43+0000',
       '2019-09-20T01:50:51+0000', '2019-02-18T12:02:48+0000',
       '2013-10-10T13:57:39+0000', '2017-06-16T18:44:33+0000',
       '2015-12-25T12:28:30+0000', '2019-09-13T06:08:17+0000',
       '2019-09-10T16:43:35+0000', '2019-09-09T17:05:17+0000',
       '2019-08-24T16:32:31+0000', '2019-07-31T16:21:07+0000',
       '2019-07-29T21:50:16+0000', '2019-07-15T16:57:05+0000'],
      dtype=object)

In [12]:
pd.set_option("display.max_columns", None)
no_adoptable=dataset[dataset["status"]!="adoptable"]
no_adoptable

,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,color_secondary,color_tertiary,age,sex,size,coat,fixed,house_trained,declawed,special_needs,shots_current,env_children,env_dogs,env_cats,name,status,posted,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description,stay_duration,stay_cost
644,41330726,NV173,https://www.petfinder.com/dog/gunther-gunny-41...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,NaN,NaN,Young,Male,Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,"Gunther :Gunny\"",Meet handsome 3 year old Gunt...",2018-04-05T05:18:31+0000,Las Vegas,NV,89146,US,89009,2019-09-20,NaN,Dog,Meet handsome 3 year old Gunther. Gunther came...,108,256.88
5549,38169117,AZ414,https://www.petfinder.com/dog/annabelle-annie-...,Dog,Dog,Boxer,Pit Bull Terrier,True,False,Black,White / Cream,NaN,Adult,Female,Large,Short,True,True,NaN,False,True,NaN,NaN,False,"ANNABELLE \ANNIE\"",""You can fill out an adopti...",2017-05-26T21:43:16+0000,Chandler,AZ,85249,US,AZ,2019-09-20,NaN,Dog,You can fill out an adoption application onlin...,80,130.77
10888,45833989,NY98,https://www.petfinder.com/dog/pepper-courtesy-...,Dog,Dog,Beagle,NaN,False,False,NaN,NaN,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,True,True,True,"PEPPER \Courtesy listing\"",""This is Pepper. He...",2019-09-01T15:12:06+0000,Albany,NY,12220,US,CT,2019-09-20,NaN,Dog,This is Pepper. He is a 15 year old tri-color ...,86,180.70
11983,45515547,NY98,https://www.petfinder.com/dog/cooper-courtesy-...,Dog,Dog,Mixed Breed,NaN,False,False,NaN,NaN,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,False,"COOPER \courtesy listing\"",""Cooper is 13 years...",2019-08-06T12:15:58+0000,Albany,NY,12220,US,CT,2019-09-20,NaN,Dog,"Cooper is 13 years old, but according to a ver...",105,400.82
12495,45294115,NY98,https://www.petfinder.com/dog/daisy-courtesy-l...,Dog,Dog,Basset Hound,NaN,False,False,Brown / Chocolate,White / Cream,NaN,Senior,Female,Medium,Short,True,True,NaN,False,True,False,False,NaN,"DAISY \courtesy listing\"",""â€¢Basset Hound, fema...",2019-07-18T14:20:58+0000,Albany,NY,12220,US,CT,2019-09-20,NaN,Dog,"Ã¢Â€Â¢Basset Hound, female, Ã¢Â€Â¢10 years \n\nDelig...",57,82.61
12600,45229004,NY1436,https://www.petfinder.com/dog/elmo-momo-452290...,Dog,Dog,American Bulldog,NaN,True,False,NaN,NaN,NaN,Senior,Male,Large,Short,True,True,NaN,False,True,True,True,NaN,"Elmo \MoMo\"",""Hello i&#039;m MoMo or Elmo , 7 ...",2019-07-11T20:34:42+0000,Saugerties,NY,12477,US,CT,2019-09-20,NaN,Dog,"Hello i'm MoMo or Elmo , 7 year old, mixed bre...",73,136.30
12613,45227052,NY1436,https://www.petfinder.com/dog/bianca-pinky-452...,Dog,Dog,Mixed Breed,NaN,False,False,White / Cream,NaN,NaN,Senior,Female,Medium,Short,True,True,NaN,False,True,True,True,NaN,"Bianca \Pinky\"",""Hello I&#039;m Bianca, a fema...",2019-07-11T14:16:38+0000,Saugerties,NY,12477,US,CT,2019-09-20,NaN,Dog,"Hello I'm Bianca, a female, 7 year old mixed b...",107,231.31
17619,45569380,CA1209,https://www.petfinder.com/dog/baby-girl-455693...,Dog,Dog,Maltese,NaN,False,False,White / Cream,NaN,NaN,Senior,Female,Small,Short,True,True,NaN,False,True,True,True,NaN,"\Baby Girl\"",""This 10-year young senior is ver...",2019-08-10T16:00:35+0000,Bristow,VA,20136,US,DC,2019-09-20,NaN,Dog,This 10-year young senior is very sweet and lo...,76,263.63
18611,44694387,MD295,https://www.petfinder.com/dog/king-bert-bertie...,Dog,Dog,Fox Terrier,Chihuahua,True,False,Bicolor,NaN,NaN,Young,Male,Small,Short,True,False,NaN,False,True,False,NaN,False,"King Bert \Bertie\"",""&quot;Bertie&quot; came t...",2019-05-14T21:09:27+0000,Silver Spring,MD,20905,US,DC,2019-09-20,NaN,Dog,"\""Bertie\"" came to us from the shelter. He wa...",61,158.84
19747,36978896,VA127,https://www.petfinder.com/dog/maddie-cutie-pat...,Dog,Dog,Alaskan Malamute,NaN,False,False,Bicolor,NaN,NaN,Adult,Female,Large,NaN,True,True,NaN,False,True,NaN,NaN,False,"Maddie \Cutie Patootie!\"",""Maddie is our littl...",2016-12-15T13:33:43+0000,Gettysburg,PA,17325,US,DC,2019-09-20,NaN,Dog,Maddie is our little Miss Cutie Patootie! She ...,119,431.66
19845,33218331,VA127,https://www.petfinder.com/dog/bucky-are-u-my-h...,Dog,Dog,Alaskan Malamute,Siberian Husky,True,False,Gray / Blue / Silver,NaN,NaN,Adult,Male,Large,Medium,True,True,NaN,False,True,NaN,NaN,False,"Bucky \Are u my hooman?\"",""Born in August 2014...",2015-09-07T12:57:27+0000,Gettysburg,PA,17325,US,DC,2019-09-20,NaN,Dog,"Born in August 2014, Bucky has a great sense o...",98,346.67
22161,42092005,PA738,https://www.petfinder.com/dog/chloe-little-ras...,Dog,Dog,Pit Bull Terrier,Pointer,True,False,Black,White / Cream,NaN,Adult,Female,Medium,Short,True,False,NaN,False,True,True,True,NaN,"CHLOE \LITTLE RASCAL\"",""Meet Chloe our &quot;L...",2018-07-05T00:55:08+0000,Media,PA,19063,US,DE,2019-09-20,NaN,Dog,"Meet Chloe our \""Little Rascal.\",113,279.59
22229,39594038,PA562,https://www.petfinder.com/dog/cozi-h-wilson-lo...,Dog,Dog,Pit Bull Terrier,NaN,True,False,NaN,NaN,NaN,Young,Female,Medium,Short,True,True,NaN,False,True,True,True,NaN,"COZI H WILSON \loves children, cuddlebug\"",""01...",2017-10-07T23:48:20+0000,Feasterville,PA,19053,US,DE,2019-09-20,NaN,Dog,01.04.19\nHi Folks! IÃ¢Â€Â™m Cozi and IÃ¢Â€Â™m so gl...,88,360.84
29283,45895274,IL688,https://www.petfinder.com/dog/gibson-edgar-gib...,Dog,Dog,Labrador Retriever,NaN,True,False,Brown / Chocolate,NaN,NaN,Young,Male,Large,Short,True,True,NaN,False,True,True,True,False,"Gibson Edgar \Gibbs\"",""Gibson Edgar is a 12 mo...",2019-09-07T04:09:12+0000,Paris,IL,61944,US,IL,2019-09-20,NaN,Dog,Gibson Edgar is a 12 month old male Lab mix th...,74,121.56
30471,45964719,IN694,https://www.petfinder.com/dog/puppies-berries-...,Dog,Dog,American Staffordshire Terrier,Border Collie,True,False,Black,White / Cream,NaN,Baby,Female,Medium,Short,False,False,NaN,False,True,True,True,NaN,"PUPPIES \Berries\"",""11 Berry Pups\nIndividual ...",2019-09-13T19:39:28+0000,Mooresville,IN,46158,US,IN,2019-09-20,NaN,Dog,11 Berry Pups\nIndividual pics will be done. ...,127,429.87
31581,44538917,OH907,https://www.petfinder.com/dog/leila-courtesy-p...,Dog,Dog,Australian Shepherd,Husky,True,False,"Tricolor (Brown, Black, & White)",NaN,NaN,Adult,Female,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,"Leila \COURTESY POST\"",""THIS IS A COURTESY POS...",2019-04-25T01:56:52+0000,Ross,OH,45061,US,IN,2019-09-20,NaN,Dog,THIS IS A COURTESY POST (this means that any a...,92,188.49
31888,41430442,OH907,https://www.petfinder.com/dog/eden-in-training...,Dog,Dog,Hound,NaN,True,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Adult,Female,Medium,Short,True,False,NaN,False,True,NaN,False,NaN,"Eden \In Training\"",""Eden is estimated 3 years...",2018-04-18T13:45:46+0000,Ross,OH,45061,US,IN,2019-09-20,NaN,Dog,Eden is estimated 3 years old and weighs 40 lb...,97,238.60
33000,45907639,IN714,https://www.petfinder.com/dog/coach-chris-mack...,Dog,Dog,Chihuahua,Beagle,True,False,Yellow / Tan / Blond / Fawn,NaN,NaN,Adult,Male,Small,Short,True,True,NaN,False,True,True,True,NaN,"Coach Chris \Mack\"",""Mack is a 2 year old, 13 ...",2019-09-08T18:21:21+0000,Jeffersonville,IN,47131,US,KY,2019-09-20,NaN,Dog,"Mack is a 2 year old, 13 pound furry chihuahua...",101,478.36
33527,45362806,OH852,https://www.petfinder.com/dog/liberty-libby-45...,Dog,Dog,Pomeranian,NaN,False,False,NaN,NaN,NaN,Adult,Female,Small,Long,True,False,NaN,False,True,False,True,True,"Liberty \Libby\"",""Liberty came to us on the 3r...",2019-07-25T19:53:21+0000,Cincinnati,OH,45249,US,KY,2019-09-20,NaN,Dog,Liberty came to us on the 3rd of July - she ha...,65,185.05
34188,32590894,IN595,https://www.petfinder.com/dog/samson-sam-32590...,Dog,Dog,Mastiff,Labrador Retriever,True,False,Black,NaN,NaN,Adult,Male,Extra Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,"Samson \Sam\"",""DUE TO PROBLEMS WITH THE CURREN...",2015-06-29T23:58:09+0000,Paoli,IN,47454,US,KY,2019-09-20,NaN,Dog,DUE TO PROBLEMS WITH THE CURRENT PETFINDER UPD...,116,413.96
35065,31426754,LA256,https://www.petfinder.com/dog/sully-sullivan-3...,Dog,Dog,Pit Bull Terrier,NaN,False,False,Black,NaN,NaN,Young,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,"Sully \Sullivan\"",""Hi my name is Sully! I get ...",2015-02-07T13:06:43+0000,lake charles,LA,70601,US,LA,2019-09-20,NaN,Dog,Hi my name is Sully! I get along with most dog...,122,204.63
44830,46037827,NM133,https://www.petfinder.com/dog/periwinkle-wink-...,Dog,Dog,Australian Shepherd,Spaniel,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Female,Medium,Medium,True,True,NaN,False,True,True,True,NaN,"PERIWINKLE \WINK\"",""We take the time to post p...",2019-09-20T01:50:51+0000,Albuquerque,NM,87108,US,NM,2019-09-20,NaN,Dog,We take the time to post pertinent information...,85,296.75
53168,44044071,TN669,https://www.petfinder.com/dog/raymond-reddingt...,Dog,Dog,American Staffordshire Terrier,NaN,True,False,Red / Chestnut / Orange,NaN,NaN,Adult,Male,Medium,Medium,True,False,NaN,False,False,True,NaN,False,"Raymond \Reddington\"",""Red is a 4-5 yr old St...",2019-02-18T12:02:48+0000,Cookeville,TN,38506,US,TN,2019-09-20,NaN,Dog,Red is a 4-5 yr old Staffey mix that is a wig...,88,230.12
53539,27521132,TN577,https://www.petfinder.com/dog/norma-rose-rosie...,Dog,Dog,Yellow Labrador Retriever,American Staffordshire Terrier,True,False,Yellow / Tan / Blond / Fawn,NaN,NaN,Adult,Female,Large,Short,True,True,NaN,False,True,True,False,False,"Norma Rose \ROSIE\"",""Robyn&#039;s Nest Animal ...",2013-10-10T13:57:39+0000,Nashville,TN,37189,US,TN,2019-09-20,NaN,Dog,Robyn's Nest Animal Rescue & SanctuaryNashvill...,93,300.50
55434,38473806,VA486,https://www.petfinder.com/dog/markey-moose-384...,Dog,Dog,Hound,NaN,False,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Adult,Male,Large,Short,False,True,NaN,False,True,True,True,NaN,"Markey \Moose\"",""Markey &quot;Moose&quot; firs...",2017-06-16T18:44:33+0000,Rustburg,VA,24588,US,VA,2019-09-20,NaN,Dog,"Markey \""Moose\"" first came to us after being ...",78,71.15
55467,34101432,VA628,https://www.petfinder.com/dog/george-boy-georg...,Dog,Dog,Labrador Retriever,NaN,True,False,Yellow / Tan / Blond / Fawn,White / Cream,NaN,Young,Male,Medium,Short,True,False,NaN,False,True,NaN,NaN,NaN,"George \Boy George\"",""Contact dojennings@Comca...",2015-12-25T12:28:30+0000,Midlothian,VA,23112,US,VA,2019-09-20,NaN,Dog,Contact dojennings@Comcast.net or Debbie Jenni...,115,320.23
55915,45958435,WA581,https://www.petfinder.com/dog/skipper-45958435...,Dog,Dog,Yorkshire Terrier,Terrier,True,False,"Tricolor (Brown, Black, & White)",White / Cream,Yellow / Tan / Blond / Fawn,Young,Male,Small,Medium,True,False,NaN,False,True,NaN,True,True,"\Skipper\"",""For a quicker response please subm...",2019-09-13T06:08:17+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,For a quicker response please submit a online ...,102,338.18
55975,45927580,WA581,https://www.petfinder.com/dog/bella-45927580/w...,Dog,Dog,Chihuahua,NaN,False,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Adult,Female,Small,Short,True,True,NaN,True,True,False,True,NaN,"\Bella\"",""Meet &quot;Bella&quot; She is a ador...",2019-09-10T16:43:35+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Bella\"" She is a adorable and 7 pounds ...",102,407.51
56013,45916348,WA581,https://www.petfinder.com/dog/cody-45916348/wa...,Dog,Dog,Golden Retriever,Terrier,True,False,Bicolor,"Tricolor (Brown, Black, & White)",NaN,Adult,Male,Medium,Short,True,True,NaN,False,True,True,True,NaN,"\Cody\"",""*Please apply online at www.6dogrees....",2019-09-09T17:05:17+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,*Please apply online at www.6dogrees.com to ge...,92,164.55
56248,45733027,WA581,https://www.petfinder.com/dog/gracie-45733027/...,Dog,Dog,Papillon,Cavalier King Charles Spaniel,True,False,Golden,Red / Chestnut / Orange,NaN,Adult,Female,Small,Medium,True,True,NaN,False,True,NaN,True,NaN,"\Gracie\"",""Meet &quot;Gracie&quot; a very beau...",2019-08-24T16:32:31+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Gracie\"" a very beautiful 11 pound,fema...",82,168.54
56464,45413997,WA581,https://www.petfinder.com/dog/jameson-45413997...,Dog,Dog,Rat Terrier,Chihuahua,True,False,"Tricolor (Brown, Black, & White)",White / Cream,NaN,Young,Male,Small,NaN,True,False,NaN,False,True,False,True,True,"\Jameson\"",""Meet &quot;Jameson&quot; He is a v...",2019-07-31T16:21:07+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Jameson\"" He is a very handsome 9 pound...",108,297.27
56473,45406516,WA581,https://www.petfinder.com/dog/canelo-45406516/...,Dog,Dog,Chihuahua,Terrier,True,False,Bicolor,Golden,NaN,Adult,Male,Small,Short,True,False,NaN,False,True,False,True,NaN,"\Canelo\"",""Meet Canelo a adorable small, tan...",2019-07-29T21:50:16+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet Canelo a adorable small, tan very sweet...",94,312.10
56541,45264615,WA581,https://www.petfinder.com/dog/noni-45264615/wa...,Dog,Dog,Chihuahua,Terrier,True,False,Black,White / Cream,NaN,Adult,Female,Small,NaN,True,True,NaN,False,True,False,True,False,"\Noni\"",""Meet &quot;Noni&quot; She is a Black ...",2019-07-15T16:57:05+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Noni\"" She is a Black and white smooth ...",77,290.16

In [13]:
righe_con_00 = dataset[dataset['status'].astype(str).str.endswith("00")]
dataset.loc[righe_con_00.index, 'status'] = np.nan

In [14]:
no_adoptable=dataset[dataset["status"]!="adoptable"]
no_adoptable

,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,color_secondary,color_tertiary,age,sex,size,coat,fixed,house_trained,declawed,special_needs,shots_current,env_children,env_dogs,env_cats,name,status,posted,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description,stay_duration,stay_cost
644,41330726,NV173,https://www.petfinder.com/dog/gunther-gunny-41...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,NaN,NaN,Young,Male,Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,"Gunther :Gunny\"",Meet handsome 3 year old Gunt...",NaN,Las Vegas,NV,89146,US,89009,2019-09-20,NaN,Dog,Meet handsome 3 year old Gunther. Gunther came...,108,256.88
5549,38169117,AZ414,https://www.petfinder.com/dog/annabelle-annie-...,Dog,Dog,Boxer,Pit Bull Terrier,True,False,Black,White / Cream,NaN,Adult,Female,Large,Short,True,True,NaN,False,True,NaN,NaN,False,"ANNABELLE \ANNIE\"",""You can fill out an adopti...",NaN,Chandler,AZ,85249,US,AZ,2019-09-20,NaN,Dog,You can fill out an adoption application onlin...,80,130.77
10888,45833989,NY98,https://www.petfinder.com/dog/pepper-courtesy-...,Dog,Dog,Beagle,NaN,False,False,NaN,NaN,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,True,True,True,"PEPPER \Courtesy listing\"",""This is Pepper. He...",NaN,Albany,NY,12220,US,CT,2019-09-20,NaN,Dog,This is Pepper. He is a 15 year old tri-color ...,86,180.70
11983,45515547,NY98,https://www.petfinder.com/dog/cooper-courtesy-...,Dog,Dog,Mixed Breed,NaN,False,False,NaN,NaN,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,False,"COOPER \courtesy listing\"",""Cooper is 13 years...",NaN,Albany,NY,12220,US,CT,2019-09-20,NaN,Dog,"Cooper is 13 years old, but according to a ver...",105,400.82
12495,45294115,NY98,https://www.petfinder.com/dog/daisy-courtesy-l...,Dog,Dog,Basset Hound,NaN,False,False,Brown / Chocolate,White / Cream,NaN,Senior,Female,Medium,Short,True,True,NaN,False,True,False,False,NaN,"DAISY \courtesy listing\"",""â€¢Basset Hound, fema...",NaN,Albany,NY,12220,US,CT,2019-09-20,NaN,Dog,"Ã¢Â€Â¢Basset Hound, female, Ã¢Â€Â¢10 years \n\nDelig...",57,82.61
12600,45229004,NY1436,https://www.petfinder.com/dog/elmo-momo-452290...,Dog,Dog,American Bulldog,NaN,True,False,NaN,NaN,NaN,Senior,Male,Large,Short,True,True,NaN,False,True,True,True,NaN,"Elmo \MoMo\"",""Hello i&#039;m MoMo or Elmo , 7 ...",NaN,Saugerties,NY,12477,US,CT,2019-09-20,NaN,Dog,"Hello i'm MoMo or Elmo , 7 year old, mixed bre...",73,136.30
12613,45227052,NY1436,https://www.petfinder.com/dog/bianca-pinky-452...,Dog,Dog,Mixed Breed,NaN,False,False,White / Cream,NaN,NaN,Senior,Female,Medium,Short,True,True,NaN,False,True,True,True,NaN,"Bianca \Pinky\"",""Hello I&#039;m Bianca, a fema...",NaN,Saugerties,NY,12477,US,CT,2019-09-20,NaN,Dog,"Hello I'm Bianca, a female, 7 year old mixed b...",107,231.31
17619,45569380,CA1209,https://www.petfinder.com/dog/baby-girl-455693...,Dog,Dog,Maltese,NaN,False,False,White / Cream,NaN,NaN,Senior,Female,Small,Short,True,True,NaN,False,True,True,True,NaN,"\Baby Girl\"",""This 10-year young senior is ver...",NaN,Bristow,VA,20136,US,DC,2019-09-20,NaN,Dog,This 10-year young senior is very sweet and lo...,76,263.63
18611,44694387,MD295,https://www.petfinder.com/dog/king-bert-bertie...,Dog,Dog,Fox Terrier,Chihuahua,True,False,Bicolor,NaN,NaN,Young,Male,Small,Short,True,False,NaN,False,True,False,NaN,False,"King Bert \Bertie\"",""&quot;Bertie&quot; came t...",NaN,Silver Spring,MD,20905,US,DC,2019-09-20,NaN,Dog,"\""Bertie\"" came to us from the shelter. He wa...",61,158.84
19747,36978896,VA127,https://www.petfinder.com/dog/maddie-cutie-pat...,Dog,Dog,Alaskan Malamute,NaN,False,False,Bicolor,NaN,NaN,Adult,Female,Large,NaN,True,True,NaN,False,True,NaN,NaN,False,"Maddie \Cutie Patootie!\"",""Maddie is our littl...",NaN,Gettysburg,PA,17325,US,DC,2019-09-20,NaN,Dog,Maddie is our little Miss Cutie Patootie! She ...,119,431.66
19845,33218331,VA127,https://www.petfinder.com/dog/bucky-are-u-my-h...,Dog,Dog,Alaskan Malamute,Siberian Husky,True,False,Gray / Blue / Silver,NaN,NaN,Adult,Male,Large,Medium,True,True,NaN,False,True,NaN,NaN,False,"Bucky \Are u my hooman?\"",""Born in August 2014...",NaN,Gettysburg,PA,17325,US,DC,2019-09-20,NaN,Dog,"Born in August 2014, Bucky has a great sense o...",98,346.67
22161,42092005,PA738,https://www.petfinder.com/dog/chloe-little-ras...,Dog,Dog,Pit Bull Terrier,Pointer,True,False,Black,White / Cream,NaN,Adult,Female,Medium,Short,True,False,NaN,False,True,True,True,NaN,"CHLOE \LITTLE RASCAL\"",""Meet Chloe our &quot;L...",NaN,Media,PA,19063,US,DE,2019-09-20,NaN,Dog,"Meet Chloe our \""Little Rascal.\",113,279.59
22229,39594038,PA562,https://www.petfinder.com/dog/cozi-h-wilson-lo...,Dog,Dog,Pit Bull Terrier,NaN,True,False,NaN,NaN,NaN,Young,Female,Medium,Short,True,True,NaN,False,True,True,True,NaN,"COZI H WILSON \loves children, cuddlebug\"",""01...",NaN,Feasterville,PA,19053,US,DE,2019-09-20,NaN,Dog,01.04.19\nHi Folks! IÃ¢Â€Â™m Cozi and IÃ¢Â€Â™m so gl...,88,360.84
29283,45895274,IL688,https://www.petfinder.com/dog/gibson-edgar-gib...,Dog,Dog,Labrador Retriever,NaN,True,False,Brown / Chocolate,NaN,NaN,Young,Male,Large,Short,True,True,NaN,False,True,True,True,False,"Gibson Edgar \Gibbs\"",""Gibson Edgar is a 12 mo...",NaN,Paris,IL,61944,US,IL,2019-09-20,NaN,Dog,Gibson Edgar is a 12 month old male Lab mix th...,74,121.56
30471,45964719,IN694,https://www.petfinder.com/dog/puppies-berries-...,Dog,Dog,American Staffordshire Terrier,Border Collie,True,False,Black,White / Cream,NaN,Baby,Female,Medium,Short,False,False,NaN,False,True,True,True,NaN,"PUPPIES \Berries\"",""11 Berry Pups\nIndividual ...",NaN,Mooresville,IN,46158,US,IN,2019-09-20,NaN,Dog,11 Berry Pups\nIndividual pics will be done. ...,127,429.87
31581,44538917,OH907,https://www.petfinder.com/dog/leila-courtesy-p...,Dog,Dog,Australian Shepherd,Husky,True,False,"Tricolor (Brown, Black, & White)",NaN,NaN,Adult,Female,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,"Leila \COURTESY POST\"",""THIS IS A COURTESY POS...",NaN,Ross,OH,45061,US,IN,2019-09-20,NaN,Dog,THIS IS A COURTESY POST (this means that any a...,92,188.49
31888,41430442,OH907,https://www.petfinder.com/dog/eden-in-training...,Dog,Dog,Hound,NaN,True,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Adult,Female,Medium,Short,True,False,NaN,False,True,NaN,False,NaN,"Eden \In Training\"",""Eden is estimated 3 years...",NaN,Ross,OH,45061,US,IN,2019-09-20,NaN,Dog,Eden is estimated 3 years old and weighs 40 lb...,97,238.60
33000,45907639,IN714,https://www.petfinder.com/dog/coach-chris-mack...,Dog,Dog,Chihuahua,Beagle,True,False,Yellow / Tan / Blond / Fawn,NaN,NaN,Adult,Male,Small,Short,True,True,NaN,False,True,True,True,NaN,"Coach Chris \Mack\"",""Mack is a 2 year old, 13 ...",NaN,Jeffersonville,IN,47131,US,KY,2019-09-20,NaN,Dog,"Mack is a 2 year old, 13 pound furry chihuahua...",101,478.36
33527,45362806,OH852,https://www.petfinder.com/dog/liberty-libby-45...,Dog,Dog,Pomeranian,NaN,False,False,NaN,NaN,NaN,Adult,Female,Small,Long,True,False,NaN,False,True,False,True,True,"Liberty \Libby\"",""Liberty came to us on the 3r...",NaN,Cincinnati,OH,45249,US,KY,2019-09-20,NaN,Dog,Liberty came to us on the 3rd of July - she ha...,65,185.05
34188,32590894,IN595,https://www.petfinder.com/dog/samson-sam-32590...,Dog,Dog,Mastiff,Labrador Retriever,True,False,Black,NaN,NaN,Adult,Male,Extra Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,"Samson \Sam\"",""DUE TO PROBLEMS WITH THE CURREN...",NaN,Paoli,IN,47454,US,KY,2019-09-20,NaN,Dog,DUE TO PROBLEMS WITH THE CURRENT PETFINDER UPD...,116,413.96
35065,31426754,LA256,https://www.petfinder.com/dog/sully-sullivan-3...,Dog,Dog,Pit Bull Terrier,NaN,False,False,Black,NaN,NaN,Young,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,"Sully \Sullivan\"",""Hi my name is Sully! I get ...",NaN,lake charles,LA,70601,US,LA,2019-09-20,NaN,Dog,Hi my name is Sully! I get along with most dog...,122,204.63
44830,46037827,NM133,https://www.petfinder.com/dog/periwinkle-wink-...,Dog,Dog,Australian Shepherd,Spaniel,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Female,Medium,Medium,True,True,NaN,False,True,True,True,NaN,"PERIWINKLE \WINK\"",""We take the time to post p...",NaN,Albuquerque,NM,87108,US,NM,2019-09-20,NaN,Dog,We take the time to post pertinent information...,85,296.75
53168,44044071,TN669,https://www.petfinder.com/dog/raymond-reddingt...,Dog,Dog,American Staffordshire Terrier,NaN,True,False,Red / Chestnut / Orange,NaN,NaN,Adult,Male,Medium,Medium,True,False,NaN,False,False,True,NaN,False,"Raymond \Reddington\"",""Red is a 4-5 yr old St...",NaN,Cookeville,TN,38506,US,TN,2019-09-20,NaN,Dog,Red is a 4-5 yr old Staffey mix that is a wig...,88,230.12
53539,27521132,TN577,https://www.petfinder.com/dog/norma-rose-rosie...,Dog,Dog,Yellow Labrador Retriever,American Staffordshire Terrier,True,False,Yellow / Tan / Blond / Fawn,NaN,NaN,Adult,Female,Large,Short,True,True,NaN,False,True,True,False,False,"Norma Rose \ROSIE\"",""Robyn&#039;s Nest Animal ...",NaN,Nashville,TN,37189,US,TN,2019-09-20,NaN,Dog,Robyn's Nest Animal Rescue & SanctuaryNashvill...,93,300.50
55434,38473806,VA486,https://www.petfinder.com/dog/markey-moose-384...,Dog,Dog,Hound,NaN,False,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Adult,Male,Large,Short,False,True,NaN,False,True,True,True,NaN,"Markey \Moose\"",""Markey &quot;Moose&quot; firs...",NaN,Rustburg,VA,24588,US,VA,2019-09-20,NaN,Dog,"Markey \""Moose\"" first came to us after being ...",78,71.15
55467,34101432,VA628,https://www.petfinder.com/dog/george-boy-georg...,Dog,Dog,Labrador Retriever,NaN,True,False,Yellow / Tan / Blond / Fawn,White / Cream,NaN,Young,Male,Medium,Short,True,False,NaN,False,True,NaN,NaN,NaN,"George \Boy George\"",""Contact dojennings@Comca...",NaN,Midlothian,VA,23112,US,VA,2019-09-20,NaN,Dog,Contact dojennings@Comcast.net or Debbie Jenni...,115,320.23
55915,45958435,WA581,https://www.petfinder.com/dog/skipper-45958435...,Dog,Dog,Yorkshire Terrier,Terrier,True,False,"Tricolor (Brown, Black, & White)",White / Cream,Yellow / Tan / Blond / Fawn,Young,Male,Small,Medium,True,False,NaN,False,True,NaN,True,True,"\Skipper\"",""For a quicker response please subm...",NaN,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,For a quicker response please submit a online ...,102,338.18
55975,45927580,WA581,https://www.petfinder.com/dog/bella-45927580/w...,Dog,Dog,Chihuahua,NaN,False,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Adult,Female,Small,Short,True,True,NaN,True,True,False,True,NaN,"\Bella\"",""Meet &quot;Bella&quot; She is a ador...",NaN,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Bella\"" She is a adorable and 7 pounds ...",102,407.51
56013,45916348,WA581,https://www.petfinder.com/dog/cody-45916348/wa...,Dog,Dog,Golden Retriever,Terrier,True,False,Bicolor,"Tricolor (Brown, Black, & White)",NaN,Adult,Male,Medium,Short,True,True,NaN,False,True,True,True,NaN,"\Cody\"",""*Please apply online at www.6dogrees....",NaN,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,*Please apply online at www.6dogrees.com to ge...,92,164.55
56248,45733027,WA581,https://www.petfinder.com/dog/gracie-45733027/...,Dog,Dog,Papillon,Cavalier King Charles Spaniel,True,False,Golden,Red / Chestnut / Orange,NaN,Adult,Female,Small,Medium,True,True,NaN,False,True,NaN,True,NaN,"\Gracie\"",""Meet &quot;Gracie&quot; a very beau...",NaN,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Gracie\"" a very beautiful 11 pound,fema...",82,168.54
56464,45413997,WA581,https://www.petfinder.com/dog/jameson-45413997...,Dog,Dog,Rat Terrier,Chihuahua,True,False,"Tricolor (Brown, Black, & White)",White / Cream,NaN,Young,Male,Small,NaN,True,False,NaN,False,True,False,True,True,"\Jameson\"",""Meet &quot;Jameson&quot; He is a v...",NaN,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Jameson\"" He is a very handsome 9 pound...",108,297.27
56473,45406516,WA581,https://www.petfinder.com/dog/canelo-45406516/...,Dog,Dog,Chihuahua,Terrier,True,False,Bicolor,Golden,NaN,Adult,Male,Small,Short,True,False,NaN,False,True,False,True,NaN,"\Canelo\"",""Meet Canelo a adorable small, tan...",NaN,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet Canelo a adorable small, tan very sweet...",94,312.10
56541,45264615,WA581,https://www.petfinder.com/dog/noni-45264615/wa...,Dog,Dog,Chihuahua,Terrier,True,False,Black,White / Cream,NaN,Adult,Female,Small,NaN,True,True,NaN,False,True,False,True,False,"\Noni\"",""Meet &quot;Noni&quot; She is a Black ...",NaN,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Noni\"" She is a Black and white smooth ...",77,290.16

**2. For each (primary) breed, determine the number of dogs**

In [15]:
breed_counts = dataset.groupby("breed_primary").size()
breed_counts

breed_primary
Affenpinscher                         17
Afghan Hound                           4
Airedale Terrier                      19
Akbash                                 3
Akita                                181
                                    ...
Wirehaired Pointing Griffon            1
Wirehaired Terrier                    60
Xoloitzcuintli / Mexican Hairless     11
Yellow Labrador Retriever            158
Yorkshire Terrier                    360
Length: 216, dtype: int64

**3. For each (primary) breed, determine the ratio between the number of dogs of Mixed Breed and those not of Mixed Breed. Hint: look at the secondary_breed.**

In [3]:
dataset['mixed_breed2'] = dataset['breed_primary'] != dataset['breed_secondary']

total_counts = dataset.groupby('breed_primary')['mixed_breed2'].count()

mixed_counts = dataset[dataset['mixed_breed2'] == True].groupby('breed_primary')['mixed_breed2'].count()
non_mixed_counts = total_counts - mixed_counts

percent_mixed = (mixed_counts / total_counts) * 100
percent_non_mixed = 100 - percent_mixed

result_df = pd.DataFrame({'NÂ° Mixed Dog': mixed_counts, 'NÂ° Non Mixed Dog': non_mixed_counts, 
                          'percent mixed': percent_mixed.map('{:.2f}%'.format), 
                          'percent non mixed': percent_non_mixed.map('{:.2f}%'.format)})

print(result_df)

                                   NÂ° Mixed Dog  NÂ° Non Mixed Dog  \
breed_primary
Affenpinscher                                17                 0
Afghan Hound                                  4                 0
Airedale Terrier                             19                 0
Akbash                                        3                 0
Akita                                       181                 0
...                                         ...               ...
Wirehaired Pointing Griffon                   1                 0
Wirehaired Terrier                           60                 0
Xoloitzcuintli / Mexican Hairless            11                 0
Yellow Labrador Retriever                   158                 0
Yorkshire Terrier                           360                 0

                                  percent mixed percent non mixed
breed_primary
Affenpinscher                           100.00%             0.00%
Afghan Hound                            100.00%             0.00%
Airedale Terrier                        100.00%             0.00%
Akbash                                  100.00%             0.00%
Akita                                   100.00%             0.00%
...                                         ...               ...
Wirehaired Pointing Griffon             100.00%             0.00%
Wirehaired Terrier                      100.00%             0.00%
Xoloitzcuintli / Mexican Hairless       100.00%             0.00%
Yellow Labrador Retriever               100.00%             0.00%
Yorkshire Terrier                       100.00%             0.00%

[216 rows x 4 columns]

In [17]:
dataset['y_mix']=dataset['breed_secondary']=='Mixed Breed'
dataset['n_mix']=dataset['breed_secondary']!='Mixed Breed'
ratio= dataset[['breed_primary', 'y_mix', 'n_mix']].groupby('breed_primary').sum() 
ratio['ratio']=ratio['y_mix']/ratio['n_mix']
ratio

                                   y_mix  n_mix     ratio
breed_primary
Affenpinscher                          1     16  0.062500
Afghan Hound                           0      4  0.000000
Airedale Terrier                       1     18  0.055556
Akbash                                 0      3  0.000000
Akita                                  6    175  0.034286
...                                  ...    ...       ...
Wirehaired Pointing Griffon            0      1  0.000000
Wirehaired Terrier                     4     56  0.071429
Xoloitzcuintli / Mexican Hairless      0     11  0.000000
Yellow Labrador Retriever              0    158  0.000000
Yorkshire Terrier                     15    345  0.043478

[216 rows x 3 columns]

In [18]:
import pandas as pd


total_counts = dataset.groupby('breed_primary')['breed_mixed'].count()

mixed_counts = dataset[dataset['breed_mixed'] == True].groupby('breed_primary')['breed_mixed'].count()
non_mixed_counts = total_counts - mixed_counts

percent_mixed = (mixed_counts / total_counts) * 100
percent_non_mixed = 100 - percent_mixed

result_df2 = pd.DataFrame({'NÂ° Mixed Dog': mixed_counts, 'NÂ° Non Mixed Dog': non_mixed_counts, 
                          'percent mixed': percent_mixed.map('{:.2f}%'.format), 
                          'percent non mixed': percent_non_mixed.map('{:.2f}%'.format)})

# Visualizza il risultato
print(result_df2)

                                   NÂ° Mixed Dog  NÂ° Non Mixed Dog  \
breed_primary
Affenpinscher                               5.0              12.0
Afghan Hound                                4.0               0.0
Airedale Terrier                           17.0               2.0
Akbash                                      2.0               1.0
Akita                                      83.0              98.0
...                                         ...               ...
Wirehaired Pointing Griffon                 1.0               0.0
Wirehaired Terrier                         45.0              15.0
Xoloitzcuintli / Mexican Hairless           5.0               6.0
Yellow Labrador Retriever                 122.0              36.0
Yorkshire Terrier                         203.0             157.0

                                  percent mixed percent non mixed
breed_primary
Affenpinscher                            29.41%            70.59%
Afghan Hound                            100.00%             0.00%
Airedale Terrier                         89.47%            10.53%
Akbash                                   66.67%            33.33%
Akita                                    45.86%            54.14%
...                                         ...               ...
Wirehaired Pointing Griffon             100.00%             0.00%
Wirehaired Terrier                       75.00%            25.00%
Xoloitzcuintli / Mexican Hairless        45.45%            54.55%
Yellow Labrador Retriever                77.22%            22.78%
Yorkshire Terrier                        56.39%            43.61%

[216 rows x 4 columns]

**4. For each (primary) breed, determine the earliest and the latest posted timestamp.**

In [19]:
import numpy as np

nome_colonna = "posted"

righe_non_terminanti_con_00 = dataset[~dataset[nome_colonna].str.endswith("00")]
luoghi_senza_numeri = [
    "Las Vegas",
    "Chandler",
    "Albany",
    "Saugerties",
    "Bristow",
    "Silver Spring",
    "Gettysburg",
    "Media",
    "Feasterville",
    "Paris",
    "Mooresville",
    "Ross",
    "Jeffersonville",
    "Cincinnati",
    "Paoli",
    "lake charles",
    "Albuquerque",
    "Cookeville",
    "Nashville",
    "Rustburg",
    "Midlothian",
    "Seattle"
]

righe_non_terminanti_con_00["posted"] = righe_non_terminanti_con_00["posted"].apply(lambda x: np.nan if any(luogo in x for luogo in luoghi_senza_numeri) else x)

for indice, nuovo_valore in righe_non_terminanti_con_00["posted"].items():
    dataset.at[indice, "posted"] = nuovo_valore

dataset

C:\Users\Piergiorgio\AppData\Local\Temp\ipykernel_19020\2394353082.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  righe_non_terminanti_con_00["posted"] = righe_non_terminanti_con_00["posted"].apply(lambda x: np.nan if any(luogo in x for luogo in luoghi_senza_numeri) else x)

,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,color_secondary,color_tertiary,age,sex,size,coat,fixed,house_trained,declawed,special_needs,shots_current,env_children,env_dogs,env_cats,name,status,posted,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description,stay_duration,stay_cost,y_mix,n_mix
0,46042150,NV163,https://www.petfinder.com/dog/harley-46042150/...,Dog,Dog,American Staffordshire Terrier,Mixed Breed,True,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,HARLEY,adoptable,2019-09-20T16:37:59+0000,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,Harley is not sure how he wound up at shelter ...,70,124.81,True,False
1,46042002,NV163,https://www.petfinder.com/dog/biggie-46042002/...,Dog,Dog,Pit Bull Terrier,Mixed Breed,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Male,Large,Short,True,True,NaN,False,True,NaN,NaN,NaN,BIGGIE,adoptable,2019-09-20T16:24:57+0000,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,6 year old Biggie has lost his home and really...,49,122.07,True,False
2,46040898,NV99,https://www.petfinder.com/dog/ziggy-46040898/n...,Dog,Dog,Shepherd,NaN,False,False,Brindle,NaN,NaN,Adult,Male,Large,Short,True,False,NaN,False,True,NaN,NaN,NaN,Ziggy,adoptable,2019-09-20T14:10:11+0000,Mesquite,NV,89027,US,89009,2019-09-20,Dog,Approx 2 years old.\n Did I catch your eye? I ...,87,281.51,False,True
3,46039877,NV202,https://www.petfinder.com/dog/gypsy-46039877/n...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,NaN,NaN,Baby,Female,Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,Gypsy,adoptable,2019-09-20T10:08:22+0000,Pahrump,NV,89048,US,89009,2019-09-20,Dog,NaN,62,145.83,False,True
4,46039306,NV184,https://www.petfinder.com/dog/theo-46039306/nv...,Dog,Dog,Dachshund,NaN,False,False,NaN,NaN,NaN,Young,Male,Small,Long,True,False,NaN,False,True,True,True,True,Theo,adoptable,2019-09-20T06:48:30+0000,Henderson,NV,89052,US,89009,2019-09-20,Dog,Theo is a friendly dachshund mix who gets alon...,93,241.09,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58175,44605893,WY20,https://www.petfinder.com/dog/tren-44605893/wy...,Dog,Dog,Border Collie,NaN,False,False,"Tricolor (Brown, Black, & White)",NaN,NaN,Adult,Male,Medium,Medium,True,True,NaN,False,False,NaN,NaN,NaN,Tren,adoptable,2019-05-03T14:23:49+0000,Lander,WY,82520,US,WY,2019-09-20,Dog,"Due to the small size of our volunteer base, w...",100,324.34,False,True
58176,44457061,WY24,https://www.petfinder.com/dog/harley-44457061/...,Dog,Dog,Australian Shepherd,Australian Cattle Dog / Blue Heeler,True,False,NaN,NaN,NaN,Young,Female,Medium,NaN,True,False,NaN,False,False,False,False,False,Harley,adoptable,2019-04-13T16:20:24+0000,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,65,245.90,False,True
58177,42865848,WY20,https://www.petfinder.com/dog/echo-42865848/wy...,Dog,Dog,Border Collie,NaN,False,False,NaN,NaN,NaN,Adult,Female,Medium,Medium,True,True,NaN,False,True,NaN,NaN,NaN,Echo,adoptable,2018-09-27T04:18:56+0000,Glenrock,WY,82637,US,WY,2019-09-20,Dog,"Due to the small size of our volunteer base, w...",100,184.06,False,True
58178,42734734,WY24,https://www.petfinder.com/dog/simon-42734734/w...,Dog,Dog,Boxer,Mixed Breed,True,False,NaN,NaN,NaN,Senior,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Simon,adoptable,2018-09-12T05:03:38+0000,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,58,61.05,True,False
58179,42663515,WY24,https://www.petfinder.com/dog/romeo-42663515/w...,Dog,Dog,Labrador Retriever,Pit Bull Terrier,True,False,NaN,NaN,NaN,Adult,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Romeo,adoptable,2018-09-03T20:42:24+0000,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,100,255.38,False,True

In [20]:
dataset["posted"] = pd.to_datetime(dataset["posted"])

def min_max_dates(series):
    return pd.Series({"earliest": series.min(), "latest": series.max()})

breed_timestamps = dataset.groupby("breed_primary")["posted"].apply(min_max_dates).reset_index()

breed_timestamps.rename(columns={"earliest": "min_posted", "latest": "max_posted"}, inplace=True)

print(breed_timestamps)

                         breed_primary   level_1                    posted
0                        Affenpinscher  earliest 2012-03-08 10:27:33+00:00
1                        Affenpinscher    latest 2019-09-14 10:10:51+00:00
2                         Afghan Hound  earliest 2017-06-29 23:28:51+00:00
3                         Afghan Hound    latest 2019-07-27 00:38:48+00:00
4                     Airedale Terrier  earliest 2014-06-13 12:59:36+00:00
..                                 ...       ...                       ...
427  Xoloitzcuintli / Mexican Hairless    latest 2019-09-08 11:15:54+00:00
428          Yellow Labrador Retriever  earliest 2010-05-31 00:00:00+00:00
429          Yellow Labrador Retriever    latest 2019-09-20 06:30:27+00:00
430                  Yorkshire Terrier  earliest 2012-02-04 17:14:52+00:00
431                  Yorkshire Terrier    latest 2019-09-20 16:56:38+00:00

[432 rows x 3 columns]

**5. For each state, compute the sex imbalance, that is the difference between male and female dogs. In which state this imbalance is largest?**

In [21]:
stati_squilibrio = dataset.groupby("contact_state")["sex"].apply(lambda x: (x == "Male").sum() - (x == "Female").sum())

stato_max_squilibrio = stati_squilibrio.idxmax()
valore_max_squilibrio = stati_squilibrio.max()

print("Stato con lo squilibrio piÃ¹ grande:", stato_max_squilibrio)
print("Valore dello squilibrio:", valore_max_squilibrio)

Stato con lo squilibrio piÃ¹ grande: OH
Valore dello squilibrio: 208

**6. For each pair (age, size), determine the average duration of the stay and the average cost of stay.**

In [22]:
raggruppamento = dataset.groupby(["age", "size"]).agg({
    "stay_duration": "mean",
    "stay_cost": "mean"
}).reset_index()

print(raggruppamento)

       age         size  stay_duration   stay_cost
0    Adult  Extra Large      89.015414  232.591561
1    Adult        Large      89.531943  238.661141
2    Adult       Medium      89.421036  238.258977
3    Adult        Small      89.407479  238.974838
4     Baby  Extra Large      87.032967  237.180879
5     Baby        Large      89.701564  238.698827
6     Baby       Medium      89.577668  237.108131
7     Baby        Small      89.958291  239.083810
8   Senior  Extra Large      88.861111  235.232361
9   Senior        Large      88.984298  237.507364
10  Senior       Medium      89.810052  238.514615
11  Senior        Small      89.073626  238.282286
12   Young  Extra Large      90.586345  245.835582
13   Young        Large      90.104206  238.149506
14   Young       Medium      89.515123  239.304603
15   Young        Small      89.814275  241.540069

**7. Find the dogs involved in at least 3 travels. Also list the breed of those dogs.**

In [23]:
viaggi_per_cane = dataset1["id"].value_counts()

cani_almeno_3_viaggi = viaggi_per_cane[viaggi_per_cane >= 3]

dataset_cani_almeno_3_viaggi = dataset[dataset["id"].isin(cani_almeno_3_viaggi.index)]

elenco_razze = dataset_cani_almeno_3_viaggi[["id", "breed_primary"]].drop_duplicates()

print("Cani coinvolti in almeno 3 viaggi e le loro razze:")
print(elenco_razze)

Cani coinvolti in almeno 3 viaggi e le loro razze:
             id        breed_primary
1159   45642530                Jindo
6835   46039420        Border Collie
8526   40036107     Pit Bull Terrier
10681  45851842   Labrador Retriever
10803  45841145          Mixed Breed
...         ...                  ...
56850  41144335            Chihuahua
56864  40103682          Rat Terrier
56875  38664932     Pit Bull Terrier
56879  38495992     Pit Bull Terrier
57263  45588395  German Shepherd Dog

[563 rows x 2 columns]

**8. Fix the travels table so that the correct state is computed from the manual and the found fields. If manual is not missing, then it overrides what is stored in found.**

In [24]:
def calculate_correct_state(row):
    if not pd.isnull(row["manual"]):
        return row["manual"]
    else:
        return row["found"]

dataset1["correct_state"] = dataset1.apply(calculate_correct_state, axis=1)
dataset1

,index,id,contact_city,contact_state,description,found,manual,remove,still_there,correct_state
0,0,44520267,Anoka,MN,Boris is a handsome mini schnauzer who made hi...,Arkansas,NaN,NaN,NaN,Arkansas
1,1,44698509,Groveland,FL,Duke is an almost 2 year old Potcake from Abac...,Abacos,Bahamas,NaN,NaN,Bahamas
2,2,45983838,Adamstown,MD,Zac Woof-ron is a heartthrob movie star lookin...,Adam,Maryland,NaN,NaN,Maryland
3,3,44475904,Saint Cloud,MN,~~Came in to the shelter as a transfer from an...,Adaptil,NaN,True,NaN,Adaptil
4,4,43877389,Pueblo,CO,Palang is such a sweetheart. She loves her peo...,Afghanistan,NaN,NaN,NaN,Afghanistan
...,...,...,...,...,...,...,...,...,...,...
6189,6189,40492179,Fairmont,WV,Please contact Pet (information@pethelpersinc....,WV,NaN,True,NaN,WV
6190,6190,45799729,Eagle Mountain,UT,Shiny is an approximately 4-6-year-old spayed ...,Wyoming,NaN,NaN,NaN,Wyoming
6191,6191,34276515,Newnan,GA,Yanni is a Male Great Pyrenees that we rescue...,Yazmin,NaN,True,NaN,Yazmin
6192,6192,44519341,Dayton,OH,Callie is a 14 year old Chihuahua whose owner ...,Young,Ohio,NaN,NaN,Ohio
6193,6193,36659999,New York,NY,This guy loves to be outside so a person w/ a ...,Zazu,NaN,True,NaN,Zazu

In [25]:
indices=dataset1[dataset1['manual'].notnull()].index
dataset1['found'][indices]=dataset1['manual'][indices]
dataset1

C:\Users\Piergiorgio\AppData\Local\Temp\ipykernel_19020\2005693385.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1['found'][indices]=dataset1['manual'][indices]

,index,id,contact_city,contact_state,description,found,manual,remove,still_there,correct_state
0,0,44520267,Anoka,MN,Boris is a handsome mini schnauzer who made hi...,Arkansas,NaN,NaN,NaN,Arkansas
1,1,44698509,Groveland,FL,Duke is an almost 2 year old Potcake from Abac...,Bahamas,Bahamas,NaN,NaN,Bahamas
2,2,45983838,Adamstown,MD,Zac Woof-ron is a heartthrob movie star lookin...,Maryland,Maryland,NaN,NaN,Maryland
3,3,44475904,Saint Cloud,MN,~~Came in to the shelter as a transfer from an...,Adaptil,NaN,True,NaN,Adaptil
4,4,43877389,Pueblo,CO,Palang is such a sweetheart. She loves her peo...,Afghanistan,NaN,NaN,NaN,Afghanistan
...,...,...,...,...,...,...,...,...,...,...
6189,6189,40492179,Fairmont,WV,Please contact Pet (information@pethelpersinc....,WV,NaN,True,NaN,WV
6190,6190,45799729,Eagle Mountain,UT,Shiny is an approximately 4-6-year-old spayed ...,Wyoming,NaN,NaN,NaN,Wyoming
6191,6191,34276515,Newnan,GA,Yanni is a Male Great Pyrenees that we rescue...,Yazmin,NaN,True,NaN,Yazmin
6192,6192,44519341,Dayton,OH,Callie is a 14 year old Chihuahua whose owner ...,Ohio,Ohio,NaN,NaN,Ohio
6193,6193,36659999,New York,NY,This guy loves to be outside so a person w/ a ...,Zazu,NaN,True,NaN,Zazu

Esercizio 8 da vedere se giusto

**9. For each state, compute the ratio between the number of travels and the population.**

In [26]:
nuova_riga = {'Alabama': 'Alabama', '5.024.279': '5.024.279'}

nuovo_df = pd.DataFrame([nuova_riga])

dataset2 = pd.concat([dataset2, nuovo_df], ignore_index=True)

nuovi_nomi_colonne = {'Alabama': 'state', '5.024.279': 'population'}
dataset2.rename(columns=nuovi_nomi_colonne, inplace=True)
dataset2

                   state  population
0                 Alaska     733.391
1                Arizona   7.151.502
2               Arkansas   3.011.524
3             California  39.538.223
4               Colorado   5.773.714
5            Connecticut   3.605.944
6               Delaware     989.948
7   District of Columbia     689.545
8                Florida  21.538.187
9                Georgia  10.711.908
10                Hawaii   1.455.271
11                 Idaho   1.839.106
12              Illinois  12.812.508
13               Indiana   6.785.528
14                  Iowa   3.190.369
15                Kansas   2.937.880
16              Kentucky   4.505.836
17             Louisiana   4.657.757
18                 Maine   1.362.359
19              Maryland   6.177.224
20         Massachusetts   7.029.917
21              Michigan  10.077.331
22             Minnesota   5.706.494
23           Mississippi   2.961.279
24              Missouri   6.154.913
25               Montana   1.084.225
26              Nebraska   1.961.504
27                Nevada   3.104.614
28         New Hampshire   1.377.529
29            New Jersey   9.288.994
30            New Mexico   2.117.522
31              New York  20.201.249
32        North Carolina  10.439.388
33          North Dakota     779.094
34                  Ohio  11.799.448
35              Oklahoma   3.959.353
36                Oregon   4.237.256
37          Pennsylvania  13.002.700
38          Rhode Island   1.097.379
39        South Carolina   5.118.425
40          South Dakota     886.667
41             Tennessee   6.910.840
42                 Texas  29.145.505
43                  Utah   3.271.616
44               Vermont     643.077
45              Virginia   8.631.393
46            Washington   7.705.281
47         West Virginia   1.793.716
48             Wisconsin   5.893.718
49               Wyoming     576.851
50               Alabama   5.024.279

In [27]:
viaggi_per_stato = dataset1.groupby("correct_state")["id"].count()

dataset2["numero_viaggi"] = dataset2["state"].map(viaggi_per_stato)

In [34]:
dataset2['population'] = dataset2['population'].str.replace('.', '', regex=True).astype(float)

dataset2['rapporto_viaggi_population'] = dataset2['numero_viaggi'] / dataset2['population']
dataset2

,state,population,numero_viaggi,rapporto_viaggi_population
0,Alaska,733391.0,NaN,NaN
1,Arizona,7151502.0,33.0,4.614415e-06
2,Arkansas,3011524.0,61.0,2.025553e-05
3,California,39538223.0,279.0,7.056463e-06
4,Colorado,5773714.0,11.0,1.905186e-06
5,Connecticut,3605944.0,16.0,4.437118e-06
6,Delaware,989948.0,27.0,2.727416e-05
7,District of Columbia,689545.0,NaN,NaN
8,Florida,21538187.0,163.0,7.567954e-06
9,Georgia,10711908.0,235.0,2.193820e-05
10,Hawaii,1455271.0,4.0,2.748629e-06
11,Idaho,1839106.0,4.0,2.174970e-06
12,Illinois,12812508.0,33.0,2.575608e-06
13,Indiana,6785528.0,17.0,2.505332e-06
14,Iowa,3190369.0,7.0,2.194104e-06
15,Kansas,2937880.0,3.0,1.021144e-06
16,Kentucky,4505836.0,99.0,2.197151e-05
17,Louisiana,4657757.0,69.0,1.481400e-05
18,Maine,1362359.0,13.0,9.542272e-06
19,Maryland,6177224.0,140.0,2.266390e-05
20,Massachusetts,7029917.0,13.0,1.849239e-06
21,Michigan,10077331.0,29.0,2.877746e-06
22,Minnesota,5706494.0,80.0,1.401912e-05
23,Mississippi,2961279.0,62.0,2.093690e-05
24,Missouri,6154913.0,17.0,2.762021e-06
25,Montana,1084225.0,NaN,NaN
26,Nebraska,1961504.0,4.0,2.039252e-06
27,Nevada,3104614.0,3.0,9.663037e-07
28,New Hampshire,1377529.0,2.0,1.451875e-06
29,New Jersey,9288994.0,44.0,4.736789e-06
30,New Mexico,2117522.0,84.0,3.966901e-05
31,New York,20201249.0,63.0,3.118619e-06
32,North Carolina,10439388.0,292.0,2.797099e-05
33,North Dakota,779094.0,2.0,2.567084e-06
34,Ohio,11799448.0,72.0,6.101980e-06
35,Oklahoma,3959353.0,32.0,8.082129e-06
36,Oregon,4237256.0,2.0,4.720036e-07
37,Pennsylvania,13002700.0,50.0,3.845355e-06
38,Rhode Island,1097379.0,4.0,3.645049e-06
39,South Carolina,5118425.0,221.0,4.317734e-05
40,South Dakota,886667.0,2.0,2.255638e-06
41,Tennessee,6910840.0,144.0,2.083683e-05
42,Texas,29145505.0,959.0,3.290387e-05
43,Utah,3271616.0,10.0,3.056593e-06
44,Vermont,643077.0,1.0,1.555024e-06
45,Virginia,8631393.0,306.0,3.545198e-05
46,Washington,7705281.0,11.0,1.427592e-06
47,West Virginia,1793716.0,117.0,6.522772e-05
48,Wisconsin,5893718.0,7.0,1.187705e-06
49,Wyoming,576851.0,1.0,1.733550e-06
50,Alabama,5024279.0,338.0,6.727333e-05

**10. For each dog, compute the number of days from the posted day to the day of last access.**

In [35]:
dataset['posted'] = pd.to_datetime(dataset['posted'])
dataset['accessed'] = pd.to_datetime(dataset['accessed'])

dataset['posted'] = dataset['posted'].dt.date
dataset['accessed'] = dataset['accessed'].dt.date

dataset['differenza_giorni'] = (dataset['accessed'] - dataset['posted']).dt.days

dataset

,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,color_secondary,color_tertiary,age,sex,size,coat,fixed,house_trained,declawed,special_needs,shots_current,env_children,env_dogs,env_cats,name,status,posted,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description,stay_duration,stay_cost,y_mix,n_mix,differenza_giorni
0,46042150,NV163,https://www.petfinder.com/dog/harley-46042150/...,Dog,Dog,American Staffordshire Terrier,Mixed Breed,True,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,HARLEY,adoptable,2019-09-20,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,Harley is not sure how he wound up at shelter ...,70,124.81,True,False,0.0
1,46042002,NV163,https://www.petfinder.com/dog/biggie-46042002/...,Dog,Dog,Pit Bull Terrier,Mixed Breed,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Male,Large,Short,True,True,NaN,False,True,NaN,NaN,NaN,BIGGIE,adoptable,2019-09-20,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,6 year old Biggie has lost his home and really...,49,122.07,True,False,0.0
2,46040898,NV99,https://www.petfinder.com/dog/ziggy-46040898/n...,Dog,Dog,Shepherd,NaN,False,False,Brindle,NaN,NaN,Adult,Male,Large,Short,True,False,NaN,False,True,NaN,NaN,NaN,Ziggy,adoptable,2019-09-20,Mesquite,NV,89027,US,89009,2019-09-20,Dog,Approx 2 years old.\n Did I catch your eye? I ...,87,281.51,False,True,0.0
3,46039877,NV202,https://www.petfinder.com/dog/gypsy-46039877/n...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,NaN,NaN,Baby,Female,Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,Gypsy,adoptable,2019-09-20,Pahrump,NV,89048,US,89009,2019-09-20,Dog,NaN,62,145.83,False,True,0.0
4,46039306,NV184,https://www.petfinder.com/dog/theo-46039306/nv...,Dog,Dog,Dachshund,NaN,False,False,NaN,NaN,NaN,Young,Male,Small,Long,True,False,NaN,False,True,True,True,True,Theo,adoptable,2019-09-20,Henderson,NV,89052,US,89009,2019-09-20,Dog,Theo is a friendly dachshund mix who gets alon...,93,241.09,False,True,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58175,44605893,WY20,https://www.petfinder.com/dog/tren-44605893/wy...,Dog,Dog,Border Collie,NaN,False,False,"Tricolor (Brown, Black, & White)",NaN,NaN,Adult,Male,Medium,Medium,True,True,NaN,False,False,NaN,NaN,NaN,Tren,adoptable,2019-05-03,Lander,WY,82520,US,WY,2019-09-20,Dog,"Due to the small size of our volunteer base, w...",100,324.34,False,True,140.0
58176,44457061,WY24,https://www.petfinder.com/dog/harley-44457061/...,Dog,Dog,Australian Shepherd,Australian Cattle Dog / Blue Heeler,True,False,NaN,NaN,NaN,Young,Female,Medium,NaN,True,False,NaN,False,False,False,False,False,Harley,adoptable,2019-04-13,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,65,245.90,False,True,160.0
58177,42865848,WY20,https://www.petfinder.com/dog/echo-42865848/wy...,Dog,Dog,Border Collie,NaN,False,False,NaN,NaN,NaN,Adult,Female,Medium,Medium,True,True,NaN,False,True,NaN,NaN,NaN,Echo,adoptable,2018-09-27,Glenrock,WY,82637,US,WY,2019-09-20,Dog,"Due to the small size of our volunteer base, w...",100,184.06,False,True,358.0
58178,42734734,WY24,https://www.petfinder.com/dog/simon-42734734/w...,Dog,Dog,Boxer,Mixed Breed,True,False,NaN,NaN,NaN,Senior,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Simon,adoptable,2018-09-12,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,58,61.05,True,False,373.0
58179,42663515,WY24,https://www.petfinder.com/dog/romeo-42663515/w...,Dog,Dog,Labrador Retriever,Pit Bull Terrier,True,False,NaN,NaN,NaN,Adult,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Romeo,adoptable,2018-09-03,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,100,255.38,False,True,382.0

In [36]:
dataset['posted'] = pd.to_datetime(dataset['posted'])
dataset['accessed'] = pd.to_datetime(dataset['accessed'])

dataset['posted'] = dataset['posted'].dt.date
dataset['accessed'] = dataset['accessed'].dt.date

dataset['diff']=dataset['accessed']-dataset['posted']
dataset

,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,color_secondary,color_tertiary,age,sex,size,coat,fixed,house_trained,declawed,special_needs,shots_current,env_children,env_dogs,env_cats,name,status,posted,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description,stay_duration,stay_cost,y_mix,n_mix,differenza_giorni,diff
0,46042150,NV163,https://www.petfinder.com/dog/harley-46042150/...,Dog,Dog,American Staffordshire Terrier,Mixed Breed,True,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,HARLEY,adoptable,2019-09-20,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,Harley is not sure how he wound up at shelter ...,70,124.81,True,False,0.0,0 days
1,46042002,NV163,https://www.petfinder.com/dog/biggie-46042002/...,Dog,Dog,Pit Bull Terrier,Mixed Breed,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Male,Large,Short,True,True,NaN,False,True,NaN,NaN,NaN,BIGGIE,adoptable,2019-09-20,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,6 year old Biggie has lost his home and really...,49,122.07,True,False,0.0,0 days
2,46040898,NV99,https://www.petfinder.com/dog/ziggy-46040898/n...,Dog,Dog,Shepherd,NaN,False,False,Brindle,NaN,NaN,Adult,Male,Large,Short,True,False,NaN,False,True,NaN,NaN,NaN,Ziggy,adoptable,2019-09-20,Mesquite,NV,89027,US,89009,2019-09-20,Dog,Approx 2 years old.\n Did I catch your eye? I ...,87,281.51,False,True,0.0,0 days
3,46039877,NV202,https://www.petfinder.com/dog/gypsy-46039877/n...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,NaN,NaN,Baby,Female,Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,Gypsy,adoptable,2019-09-20,Pahrump,NV,89048,US,89009,2019-09-20,Dog,NaN,62,145.83,False,True,0.0,0 days
4,46039306,NV184,https://www.petfinder.com/dog/theo-46039306/nv...,Dog,Dog,Dachshund,NaN,False,False,NaN,NaN,NaN,Young,Male,Small,Long,True,False,NaN,False,True,True,True,True,Theo,adoptable,2019-09-20,Henderson,NV,89052,US,89009,2019-09-20,Dog,Theo is a friendly dachshund mix who gets alon...,93,241.09,False,True,0.0,0 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58175,44605893,WY20,https://www.petfinder.com/dog/tren-44605893/wy...,Dog,Dog,Border Collie,NaN,False,False,"Tricolor (Brown, Black, & White)",NaN,NaN,Adult,Male,Medium,Medium,True,True,NaN,False,False,NaN,NaN,NaN,Tren,adoptable,2019-05-03,Lander,WY,82520,US,WY,2019-09-20,Dog,"Due to the small size of our volunteer base, w...",100,324.34,False,True,140.0,140 days
58176,44457061,WY24,https://www.petfinder.com/dog/harley-44457061/...,Dog,Dog,Australian Shepherd,Australian Cattle Dog / Blue Heeler,True,False,NaN,NaN,NaN,Young,Female,Medium,NaN,True,False,NaN,False,False,False,False,False,Harley,adoptable,2019-04-13,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,65,245.90,False,True,160.0,160 days
58177,42865848,WY20,https://www.petfinder.com/dog/echo-42865848/wy...,Dog,Dog,Border Collie,NaN,False,False,NaN,NaN,NaN,Adult,Female,Medium,Medium,True,True,NaN,False,True,NaN,NaN,NaN,Echo,adoptable,2018-09-27,Glenrock,WY,82637,US,WY,2019-09-20,Dog,"Due to the small size of our volunteer base, w...",100,184.06,False,True,358.0,358 days
58178,42734734,WY24,https://www.petfinder.com/dog/simon-42734734/w...,Dog,Dog,Boxer,Mixed Breed,True,False,NaN,NaN,NaN,Senior,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Simon,adoptable,2018-09-12,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,58,61.05,True,False,373.0,373 days
58179,42663515,WY24,https://www.petfinder.com/dog/romeo-42663515/w...,Dog,Dog,Labrador Retriever,Pit Bull Terrier,True,False,NaN,NaN,NaN,Adult,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Romeo,adoptable,2018-09-03,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,100,255.38,False,True,382.0,382 days

**11. Partition the dogs according to the number of weeks from the posted day to the day of last access.**

In [37]:
dataset['posted'] = pd.to_datetime(dataset['posted'])
dataset['accessed'] = pd.to_datetime(dataset['accessed'])

dataset['settimane_differenza'] = (dataset['accessed'] - dataset['posted']).dt.days // 7

bins = [-1, 4, 8, 12, float('inf')]  # Definisco gli intervalli delle settimane
labels = ['0-4 settimane', '5-8 settimane', '9-12 settimane', 'oltre 12 settimane']

dataset['settimane_partition'] = pd.cut(dataset['settimane_differenza'], bins=bins, labels=labels)

dataset

,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,color_secondary,color_tertiary,age,sex,size,coat,fixed,house_trained,declawed,special_needs,shots_current,env_children,env_dogs,env_cats,name,status,posted,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description,stay_duration,stay_cost,y_mix,n_mix,differenza_giorni,diff,settimane_differenza,settimane_partition
0,46042150,NV163,https://www.petfinder.com/dog/harley-46042150/...,Dog,Dog,American Staffordshire Terrier,Mixed Breed,True,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,HARLEY,adoptable,2019-09-20,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,Harley is not sure how he wound up at shelter ...,70,124.81,True,False,0.0,0 days,0.0,0-4 settimane
1,46042002,NV163,https://www.petfinder.com/dog/biggie-46042002/...,Dog,Dog,Pit Bull Terrier,Mixed Breed,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Male,Large,Short,True,True,NaN,False,True,NaN,NaN,NaN,BIGGIE,adoptable,2019-09-20,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,6 year old Biggie has lost his home and really...,49,122.07,True,False,0.0,0 days,0.0,0-4 settimane
2,46040898,NV99,https://www.petfinder.com/dog/ziggy-46040898/n...,Dog,Dog,Shepherd,NaN,False,False,Brindle,NaN,NaN,Adult,Male,Large,Short,True,False,NaN,False,True,NaN,NaN,NaN,Ziggy,adoptable,2019-09-20,Mesquite,NV,89027,US,89009,2019-09-20,Dog,Approx 2 years old.\n Did I catch your eye? I ...,87,281.51,False,True,0.0,0 days,0.0,0-4 settimane
3,46039877,NV202,https://www.petfinder.com/dog/gypsy-46039877/n...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,NaN,NaN,Baby,Female,Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,Gypsy,adoptable,2019-09-20,Pahrump,NV,89048,US,89009,2019-09-20,Dog,NaN,62,145.83,False,True,0.0,0 days,0.0,0-4 settimane
4,46039306,NV184,https://www.petfinder.com/dog/theo-46039306/nv...,Dog,Dog,Dachshund,NaN,False,False,NaN,NaN,NaN,Young,Male,Small,Long,True,False,NaN,False,True,True,True,True,Theo,adoptable,2019-09-20,Henderson,NV,89052,US,89009,2019-09-20,Dog,Theo is a friendly dachshund mix who gets alon...,93,241.09,False,True,0.0,0 days,0.0,0-4 settimane
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58175,44605893,WY20,https://www.petfinder.com/dog/tren-44605893/wy...,Dog,Dog,Border Collie,NaN,False,False,"Tricolor (Brown, Black, & White)",NaN,NaN,Adult,Male,Medium,Medium,True,True,NaN,False,False,NaN,NaN,NaN,Tren,adoptable,2019-05-03,Lander,WY,82520,US,WY,2019-09-20,Dog,"Due to the small size of our volunteer base, w...",100,324.34,False,True,140.0,140 days,20.0,oltre 12 settimane
58176,44457061,WY24,https://www.petfinder.com/dog/harley-44457061/...,Dog,Dog,Australian Shepherd,Australian Cattle Dog / Blue Heeler,True,False,NaN,NaN,NaN,Young,Female,Medium,NaN,True,False,NaN,False,False,False,False,False,Harley,adoptable,2019-04-13,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,65,245.90,False,True,160.0,160 days,22.0,oltre 12 settimane
58177,42865848,WY20,https://www.petfinder.com/dog/echo-42865848/wy...,Dog,Dog,Border Collie,NaN,False,False,NaN,NaN,NaN,Adult,Female,Medium,Medium,True,True,NaN,False,True,NaN,NaN,NaN,Echo,adoptable,2018-09-27,Glenrock,WY,82637,US,WY,2019-09-20,Dog,"Due to the small size of our volunteer base, w...",100,184.06,False,True,358.0,358 days,51.0,oltre 12 settimane
58178,42734734,WY24,https://www.petfinder.com/dog/simon-42734734/w...,Dog,Dog,Boxer,Mixed Breed,True,False,NaN,NaN,NaN,Senior,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Simon,adoptable,2018-09-12,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,58,61.05,True,False,373.0,373 days,53.0,oltre 12 settimane
58179,42663515,WY24,https://www.petfinder.com/dog/romeo-42663515/w...,Dog,Dog,Labrador Retriever,Pit Bull Terrier,True,False,NaN,NaN,NaN,Adult,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Romeo,adoptable,2018-09-03,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,100,255.38,False,True,382.0,382 days,54.0,oltre 12 settimane

**12. Find for duplicates in the dogs dataset. Two records are duplicates if they have (1) same breeds and sex, and (2) they share at least 90% of the words in the description field. Extra points if you find and implement a more refined for determining if two rows are duplicates.**

In [39]:
#cond1
no_null=dataset[dataset['description'].notna()]
no_null
a=no_null[['breed_primary', 'breed_secondary', 'sex', 'id']].groupby(['breed_primary', 'breed_secondary','sex']).count()
a= a[a['id']!=1].reset_index()
a= a.rename(columns={"id": "number"})
a

#extract id
dicti={}
for j in range(len(a)):
    dicti[j]=no_null[(no_null['breed_primary']==a.iloc[j]['breed_primary']) & (no_null['breed_secondary']==a.iloc[j]['breed_secondary'])&(no_null['sex']==a.iloc[j]['sex'])]['id']
dicti

#put id in the dataset
for i in range(len(dicti)):
    dicti[i]=dicti[i].values.tolist()
a['id_list']=dicti.values()
a

#from the dataset 'no_null', extract description associated to specific id in 
list_id = a['id_list']
b=[]
lista_def=[]
for i in range(len(list_id)):
    b=[]
    for k in range(len(list_id[i])):
        b.append(no_null[no_null['id']==list_id[i][k]]['description'].values[0])
    lista_def.append(b)
    

a['description']=lista_def
a
import nltk

from nltk.cluster.util import cosine_distance
import numpy as np
def get_cosine_similarity(sentence1, sentence2, stopwords=None):
    if stopwords is None:
        stopwords = []

    sentence1 = [w.lower() for w in sentence1]
    sentence2 = [w.lower() for w in sentence2]
    words_all = list(set(sentence1 + sentence2))

    array1 = [0] * len(words_all)
    array2 = [0] * len(words_all)

    for w in sentence1:
        if w in stopwords:
            continue
        array1[words_all.index(w)] += 1

    for w in sentence2:
        if w in stopwords:
            continue
        array2[words_all.index(w)] += 1
    return 1 - cosine_distance(array1, array2)

for i in range(len(list_id)):
    for j in range(len(list_id[i])):
        for k in range(len(list_id[i])-1,j,-1):
            x= a['description'][i][j]
            y= a['description'][i][k]
            if get_cosine_similarity(x,y, stopwords=None)>=0.9:
                S1=x
                S2=y
                Cos=get_cosine_similarity(x,y, stopwords=None)
print(f"\033[1mThe first sentence is \033[0m \n{x}\n\033[1mThe second sentence is \033[0m\n{y} \n\n\033[1mThe similarity value is equal to\033[0m {get_cosine_similarity(x,y,stopwords=None)} \n \n ")

import time 
start=time.time()
id_1=[]
id_2=[]
descr_1=[]
descr_2=[]
sim=[]
for i in range(len(list_id)):
    for j in range(len(list_id[i])):
        for k in range(len(list_id[i])-1,j,-1):
            x= a['description'][i][j]
            y= a['description'][i][k]
            if get_cosine_similarity(x,y, stopwords=None)>=0.9:
                id_1.append(a['id_list'][i][j])
                id_2.append(a['id_list'][i][k])
                descr_1.append(x)
                descr_2.append(y)
                sim.append(get_cosine_similarity(x,y, stopwords=None))
end=time.time()
t=end-start
final={'id_1':id_1, 'descr_1':descr_1, 'id_2':id_2, 'descr_2':descr_2, 'similarity':sim}
pd.DataFrame.from_dict(final)

The first sentence is
Bam Bam is approximately a 1 year old Yorkshire Terrier/Wire Haired Terrier ready to find his loving forever home!

Bam Bam is a sweet, & loving boy whom is a gorgeous little boy who loves everyone including kids, and other dogs.  His favorite thing to do is to play, & to be by your side or in your lap.

Bam Bam is fixed, microchipped and vaccinated. He would be a great addition to any family.

Fill out an application today to set up a meet & greet with this sweet boy!!

Application, Reference check, Home check and adoption fee apply.

BRAT Rescue, Inc. at this time conducts adoptions in the Five (5) boroughs of NYC, Long Island, and Southern Westchester County.

BRAT RESCUE INC., is a 501c3 tax exempt organization that rescues dog's and feeds feral animals in Far Rockaway and neighboring towns in Queens and the five boroughs of NYC.
The second sentence is
Buckeye came into our rescue from the owner.  There were issues they were unable to handle.  He was being subjected to a shock collar (he weighs 8 pounds) because it was stated he was a runner.  He also was not neutered.  Flash forward, Buckeye comes when called, is neutered and does well with all the foster dogs.  Since we do not know how he is with children, we do not recommend children under 10 years of age.  He is now a charming little guy that loves attention and gives plenty of kisses.  He is clean in his crate and enjoys his crate when the others are also crated.  He is exposed to large dogs and young puppies (not his ideal favorite) and tolerates all well.

We prefer and adopter that is not a push over but will ensure he stays a nice gentleman that he is now.  He is neutered and up to date on his vaccinations including rabies.  He is also on heartworm & flea preventative.

Buckeye is 6 years old and weighs 8.8 pounds.

Please contact kindhands4paws@gmail.com for an application.  His adoption fee is $250.00

The similarity value is equal to 0.9798076154791401

,id_1,descr_1,id_2,descr_2,similarity
0,46021163,"Mika is a blend of Akita, Husky and Shepard. S...",46021089,"Yoko is a sweet 10 week old Akita, Husky, Shep...",0.978872
1,42994498,A warrior in a small package. If you want to ...,44589975,OREO and his brother LUDY were found under a h...,0.920485
2,42994498,A warrior in a small package. If you want to ...,28662641,"This smart fellow has it all, good looks, a br...",0.937452
3,28662641,"This smart fellow has it all, good looks, a br...",44589975,OREO and his brother LUDY were found under a h...,0.973067
4,36772830,"Please note, this is a courtesy listing for ou...",34447648,Sadie is around 6-8 years old and she's a real...,0.983449
...,...,...,...,...,...
281428,45965556,"AT PEPPERMINT PIG ANIMAL RESCUE, WE UPDATE ALL...",45397822,Felix and his brother Oscar came to us from a ...,0.956428
281429,45397822,Felix and his brother Oscar came to us from a ...,45958435,For a quicker response please submit a online ...,0.971458
281430,44070750,Look at our Angel Pancho enjoying life his at ...,44822880,Buckeye came into our rescue from the owner. ...,0.972511
281431,44070750,Look at our Angel Pancho enjoying life his at ...,45407894,Bam Bam is approximately a 1 year old Yorkshir...,0.975867
281432,45407894,Bam Bam is approximately a 1 year old Yorkshir...,44822880,Buckeye came into our rescue from the owner. ...,0.979808

In [40]:
#minutes
t/60

13.532622929414114